feat(influxdb): add backup for influxdb
Suezenv/docker-images pull request #8
Opened 2019-08-22 15:17 UTC by angelfs

2019-08-27 07:07 UTC, jbouzekri requested changes

2019-08-27 07:07 UTC, jbouzekri commented on backup/influxdb/Dockerfile
> +FROM suezenv/phpbu:5.2.7
Normalement, cette version n'a pas le support influx

2019-08-27 09:52 UTC, angelfs commented on backup/influxdb/Dockerfile
> +FROM suezenv/phpbu:5.2.7
Oui bien vu, je suis en attente de la release, ca va être du 6.*: https://github.com/sebastianfeldmann/phpbu-documentation/pull/13#issuecomment-524531500

2019-08-27 09:57 UTC, jbouzekri commented on backup/influxdb/Dockerfile
> +FROM suezenv/phpbu:5.2.7
Ok on patiente alors

2019-09-12 13:07 UTC, jbouzekri approved these changes

2019-09-12 13:07 UTC, merged